name: Build OpenWrt for specific target and release

on:
  workflow_dispatch:

env:
  REMOTE_REPOSITORY: davidrapan/openwrt
  REMOTE_BRANCH: dev
  REMOTE_BRANCH_ENCODED: main
  CONFIG_FILE: ax3600.config
  PROFILE_NAME: xiaomi_ax3600
  RELEASE_PREFIX: qualcommax-6.x-wifi

jobs:
  build:
    name: Build OpenWrt
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3-setuptools rsync swig unzip zlib1g-dev file wget
      - name: Checkout remote repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REMOTE_REPOSITORY }}
          ref: ${{ env.REMOTE_BRANCH }}
      - name: Update and install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Build the firmware image
        run: make download world V=sc -j$(nproc)
      - name: Archive
        run: tar -cvf ipq807xx-images.tar bin/targets/qualcommax/ipq807x
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ipq807x-images
          path: ipq807xx-images.tar
